import { chromium } from "playwright"

const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 1280, height: 800 } })
await page.goto("http://127.0.0.1:7809")
await page.fill("#password", "qa-password-123")
await page.click("button[type=submit]")
await page.waitForSelector(".terminal canvas", { timeout: 15000 })
await page.waitForTimeout(1200)
await page.click(".terminal")
await page.keyboard.type("printf '\\e[31mRED\\e[32mGREEN\\e[34mBLUE\\e[0m 한글 🚀 theme-ok\\n'")
await page.keyboard.press("Enter")
await page.waitForTimeout(2000)
await page.screenshot({ path: "qa-evidence/d4-ghostty-theme.png" })
console.log("captured")
await browser.close()
